name: 'Configure texlive'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Building Docker Image
        run: docker build . --file Dockerfile --tag texdock
